#!/usr/bin/env bash
# A Bash script that creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminate itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid

delete_function()
{
	rm /var/run/myscript.pid
	exit
}

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && delete_func' SIGTERM
  trap 'delete_function' SIGQUIT
done
