#!/usr/bin/env bash
# This script extends previous exercise command and displays line containing the bash word, this allowing you to easily get the PID of your Bash process
# You cannot use pgrep
# The third line of your script must be # shellcheck disable=SC2009

ps -auxf | grep bash
