#!/usr/bin/env bash
# A Bash script that writes "I am alive" to the file /tmp/my_process indefinitely
#   Pauses two seconds in between each message.

while true
do
  echo "I am alive!" >> /tmp/my_process
  sleep 2
done
