#!/usr/bin/env bash
# A bash script that displays the contents of the file `/etc/passwd`.
# Only displays the username, user id, and user home directory path.

while IFS= read -r passwd;
do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
