#!/usr/bin/env bash
# A bash script is displaying "Best School" 10 times
# for the 9th iteration, displays Best School and then Hi

count=0
while [ "$count" -lt "10" ]
do
    echo "Best School"

    if [ "$count" -eq "8" ]
    then
        echo "Hi"
    fi

    count=$(( count + 1 ))
done
