#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
# Only displays the part of the name after the first dash.

list=$(ls)
for count in $list;
do
	echo "$count" | cut -d '-' -f2
done
